config/routes.rb
Rails.application.routes.draw do
  resources :engineer_classes
  resources :engineers
  resources :projects

end

app/models/engineer.rb
class Engineer < ActiveRecord::Base
end

app/models/engineer_class.rb
class EngineerClass < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/engineer_classes_controller.rb
class EngineerClassesController < ApplicationController
  before_action :set_engineer_class, only: [:show, :edit, :update, :destroy]

  # GET /engineer_classes
  # GET /engineer_classes.json
  def index
    @engineer_classes = EngineerClass.all
  end

  # GET /engineer_classes/1
  # GET /engineer_classes/1.json
  def show
  end

  # GET /engineer_classes/new
  def new
    @engineer_class = EngineerClass.new
  end

  # GET /engineer_classes/1/edit
  def edit
  end

  # POST /engineer_classes
  # POST /engineer_classes.json
  def create
    @engineer_class = EngineerClass.new(engineer_class_params)

    respond_to do |format|
      if @engineer_class.save
        format.html { redirect_to @engineer_class, notice: 'Engineer class was successfully created.' }
        format.json { render :show, status: :created, location: @engineer_class }
      else
        format.html { render :new }
        format.json { render json: @engineer_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engineer_classes/1
  # PATCH/PUT /engineer_classes/1.json
  def update
    respond_to do |format|
      if @engineer_class.update(engineer_class_params)
        format.html { redirect_to @engineer_class, notice: 'Engineer class was successfully updated.' }
        format.json { render :show, status: :ok, location: @engineer_class }
      else
        format.html { render :edit }
        format.json { render json: @engineer_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engineer_classes/1
  # DELETE /engineer_classes/1.json
  def destroy
    @engineer_class.destroy
    respond_to do |format|
      format.html { redirect_to engineer_classes_url, notice: 'Engineer class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engineer_class
      @engineer_class = EngineerClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engineer_class_params
      params.require(:engineer_class).permit(:eC_id, :e_className, :class_desc, :enabled)
    end
end

app/controllers/engineers_controller.rb
class EngineersController < ApplicationController
  before_action :set_engineer, only: [:show, :edit, :update, :destroy]

  # GET /engineers
  # GET /engineers.json
  def index
    @engineers = Engineer.all
  end

  # GET /engineers/1
  # GET /engineers/1.json
  def show
  end

  # GET /engineers/new
  def new
    @engineer = Engineer.new
  end

  # GET /engineers/1/edit
  def edit
  end

  # POST /engineers
  # POST /engineers.json
  def create
    @engineer = Engineer.new(engineer_params)

    respond_to do |format|
      if @engineer.save
        format.html { redirect_to @engineer, notice: 'Engineer was successfully created.' }
        format.json { render :show, status: :created, location: @engineer }
      else
        format.html { render :new }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engineers/1
  # PATCH/PUT /engineers/1.json
  def update
    respond_to do |format|
      if @engineer.update(engineer_params)
        format.html { redirect_to @engineer, notice: 'Engineer was successfully updated.' }
        format.json { render :show, status: :ok, location: @engineer }
      else
        format.html { render :edit }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engineers/1
  # DELETE /engineers/1.json
  def destroy
    @engineer.destroy
    respond_to do |format|
      format.html { redirect_to engineers_url, notice: 'Engineer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engineer
      @engineer = Engineer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engineer_params
      params.require(:engineer).permit(:e_id, :full_name, :class, :enabled, :accepted_projects, :status)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:p_id, :p_name, :p_desc, :p_creator, :engineer, :status, :accepted, :complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/engineer_classes_helper.rb
module EngineerClassesHelper
end

app/helpers/engineers_helper.rb
module EngineersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/engineer_classes/_form.html.erb
<%= form_for(@engineer_class) do |f| %>
  <% if @engineer_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@engineer_class.errors.count, "error") %> prohibited this engineer_class from being saved:</h2>

      <ul>
      <% @engineer_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :eC_id %><br>
    <%= f.number_field :eC_id %>
  </div>
  <div class="field">
    <%= f.label :e_className %><br>
    <%= f.text_field :e_className %>
  </div>
  <div class="field">
    <%= f.label :class_desc %><br>
    <%= f.text_area :class_desc %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br>
    <%= f.check_box :enabled %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/engineer_classes/edit.html.erb
<h1>Editing Engineer Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @engineer_class %> |
<%= link_to 'Back', engineer_classes_path %>

app/views/engineer_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Engineer Classes</h1>

<table>
  <thead>
    <tr>
      <th>Ec</th>
      <th>E classname</th>
      <th>Class desc</th>
      <th>Enabled</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @engineer_classes.each do |engineer_class| %>
      <tr>
        <td><%= engineer_class.eC_id %></td>
        <td><%= engineer_class.e_className %></td>
        <td><%= engineer_class.class_desc %></td>
        <td><%= engineer_class.enabled %></td>
        <td><%= link_to 'Show', engineer_class %></td>
        <td><%= link_to 'Edit', edit_engineer_class_path(engineer_class) %></td>
        <td><%= link_to 'Destroy', engineer_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Engineer class', new_engineer_class_path %>

app/views/engineer_classes/new.html.erb
<h1>New Engineer Class</h1>

<%= render 'form' %>

<%= link_to 'Back', engineer_classes_path %>

app/views/engineer_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ec:</strong>
  <%= @engineer_class.eC_id %>
</p>

<p>
  <strong>E classname:</strong>
  <%= @engineer_class.e_className %>
</p>

<p>
  <strong>Class desc:</strong>
  <%= @engineer_class.class_desc %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @engineer_class.enabled %>
</p>

<%= link_to 'Edit', edit_engineer_class_path(@engineer_class) %> |
<%= link_to 'Back', engineer_classes_path %>

app/views/engineers/_form.html.erb
<%= form_for(@engineer) do |f| %>
  <% if @engineer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@engineer.errors.count, "error") %> prohibited this engineer from being saved:</h2>

      <ul>
      <% @engineer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :e_id %><br>
    <%= f.number_field :e_id %>
  </div>
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :class %><br>
    <%= f.text_field :class %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br>
    <%= f.check_box :enabled %>
  </div>
  <div class="field">
    <%= f.label :accepted_projects %><br>
    <%= f.number_field :accepted_projects %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/engineers/edit.html.erb
<h1>Editing Engineer</h1>

<%= render 'form' %>

<%= link_to 'Show', @engineer %> |
<%= link_to 'Back', engineers_path %>

app/views/engineers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Engineers</h1>

<table>
  <thead>
    <tr>
      <th>E</th>
      <th>Full name</th>
      <th>Class</th>
      <th>Enabled</th>
      <th>Accepted projects</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @engineers.each do |engineer| %>
      <tr>
        <td><%= engineer.e_id %></td>
        <td><%= engineer.full_name %></td>
        <td><%= engineer.class %></td>
        <td><%= engineer.enabled %></td>
        <td><%= engineer.accepted_projects %></td>
        <td><%= engineer.status %></td>
        <td><%= link_to 'Show', engineer %></td>
        <td><%= link_to 'Edit', edit_engineer_path(engineer) %></td>
        <td><%= link_to 'Destroy', engineer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Engineer', new_engineer_path %>

app/views/engineers/new.html.erb
<h1>New Engineer</h1>

<%= render 'form' %>

<%= link_to 'Back', engineers_path %>

app/views/engineers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>E:</strong>
  <%= @engineer.e_id %>
</p>

<p>
  <strong>Full name:</strong>
  <%= @engineer.full_name %>
</p>

<p>
  <strong>Class:</strong>
  <%= @engineer.class %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @engineer.enabled %>
</p>

<p>
  <strong>Accepted projects:</strong>
  <%= @engineer.accepted_projects %>
</p>

<p>
  <strong>Status:</strong>
  <%= @engineer.status %>
</p>

<%= link_to 'Edit', edit_engineer_path(@engineer) %> |
<%= link_to 'Back', engineers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mastr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :p_id %><br>
    <%= f.number_field :p_id %>
  </div>
  <div class="field">
    <%= f.label :p_name %><br>
    <%= f.text_field :p_name %>
  </div>
  <div class="field">
    <%= f.label :p_desc %><br>
    <%= f.text_area :p_desc %>
  </div>
  <div class="field">
    <%= f.label :p_creator %><br>
    <%= f.text_field :p_creator %>
  </div>
  <div class="field">
    <%= f.label :engineer %><br>
    <%= f.text_field :engineer %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :accepted %><br>
    <%= f.check_box :accepted %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>P</th>
      <th>P name</th>
      <th>P desc</th>
      <th>P creator</th>
      <th>Engineer</th>
      <th>Status</th>
      <th>Accepted</th>
      <th>Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.p_id %></td>
        <td><%= project.p_name %></td>
        <td><%= project.p_desc %></td>
        <td><%= project.p_creator %></td>
        <td><%= project.engineer %></td>
        <td><%= project.status %></td>
        <td><%= project.accepted %></td>
        <td><%= project.complete %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>P:</strong>
  <%= @project.p_id %>
</p>

<p>
  <strong>P name:</strong>
  <%= @project.p_name %>
</p>

<p>
  <strong>P desc:</strong>
  <%= @project.p_desc %>
</p>

<p>
  <strong>P creator:</strong>
  <%= @project.p_creator %>
</p>

<p>
  <strong>Engineer:</strong>
  <%= @project.engineer %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @project.accepted %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @project.complete %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>